### ISSUE TITLE
Colours not correct in Dark Mode on High Sierra

### ISSUE THREAD

**Issue by yveslaroche** [volendavidov/NagBar#3]
Nagbar does not use the right colours anymore when using the Dark Mode on High Sierra. It did work previously on Sierra. I'm using the latest version 1.3.1.

![darkmode_high_sierra](https://user-images.githubusercontent.com/1151977/30969534-953bfa88-a45a-11e7-9e06-165d17a39a1e.png)

**Comment by volendavidov** [comment]
There was a problem in both normal and dark mode. It is fixed in https://github.com/volendavidov/NagBar/commit/94699c60b39c453da9b6aa61ac0f53024c0e9bd5 and released as [NagBar 1.3.2](https://github.com/volendavidov/NagBar/releases/tag/1.3.2)

It seems that `wantsLayer` (needed for animations) behavior has been changed in High Sierra and it somehow changes the color of the top view of the status bar to gray. Setting the color of that view to transparent solves the problem.

**Comment by timkite** [comment]
This issue is not fixed for systems with multiple displays. I opened a separate case, since it might be a separate issue, so sorry if that wasn't the right thing to do. Could it be that when toggling between displays the transparent setting is getting lost?

**Comment by volendavidov** [comment]
I tried to reproduce the issue, but everything works fine for me on multiple displays. So, it will be a bit difficult to find a solution for this. I will follow up in #4.

**Comment by yveslaroche** [comment]
@volendavidov I have the same issue and I'm also using multiple displays
